FROM golang:1.20 AS builder

WORKDIR /build

COPY go.mod go.sum ./

RUN go mod download

COPY . .

RUN CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -o myapp ./cmd

ENTRYPOINT ["/build/myapp"]
CMD ["run-worker"]